function presentacion
%***************************************************************
% presentación: SIEL
%***************************************************************
clear,clc,cla,close all
%Creamos figura
figdiag=figure('Units','Pixels','Position',[680 378 1173 720],...
'NumberTitle','off',...
'Name','SIEL', ...
'Menubar','none', ...
'color',[0 0 0]);
%Ubicamos ejes en figura
axes('Units','Normalized',...
'Position',[0 0 1 1]);
%-----Centramos la figura---------
scrsz = get(0, 'ScreenSize');
pos_act=get(gcf,'Position');
xr=scrsz(3) - pos_act(3);
xp=round(xr/2);
yr=scrsz(4) - pos_act(4);
yp=round(yr/2);
set(gcf,'Position',[xp yp pos_act(3) pos_act(4)]);
%---------------------------------------
%Incluir imagen
%Importamos imagen *.png,junto con su mapa de colores
[x,map]=imread('presentacion.png','png');
%Representamos imagen en figura, con su mapa de colores
image(x),colormap(map),axis off,hold on
%Títulos sobre imagen
%Título
text(30,60,'Matemática Superior','Fontname','Arial','Fontsize',25,'Fontangle','Italic', ...
'Fontweight','Bold','color',[0.527 0.077 0.221]);
%Botón Empezar
botok=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'fontweight', 'bold',...
'fontsize',12,...
'Position',[.84 .31 .12 .05], ...
'BackgroundColor',[0.063 0.435 0.267],...
'String','EMPEZAR',...
'Callback','clear all; close all;clc; GUI;');